include_guard(DIRECTORY)

if (DEFINED IDACMAKE)
    include(${IDACMAKE}/common.cmake)
elseif  (DEFINED ENV{IDACMAKE})
    include($ENV{IDACMAKE}/common.cmake)
elseif (DEFINED IDASDK)
    include(${IDASDK}/ida-cmake/common.cmake)
elseif (DEFINED ENV{IDASDK})
    include($ENV{IDASDK}/ida-cmake/common.cmake)
else()
    message(FATAL_ERROR "IDA SDK folder not specified via the -D switch or the environment variable 'IDASDK'")
endif()
